server:
  port: ${PORT:8083}

vnpay:
  tmnCode: ${VNP_TMN_CODE:G18S515I}
  hashSecret: ${VNP_HASH_SECRET:8VPOINLIUTBYIMFPUZSQFWRFHNJ99415}
  payUrl: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
  returnUrl: ${VNP_RETURN_URL:https://vnpayspringboot-2.onrender.com/api/vnpay/callback}
